version: "3"
services:
  node-app:
    build:
      context: . #same as location of dockerfile like we did before
      args:
        NODE_ENV: development
    volumes:
      - ./:/app # bind mount
      - /app/node_modules # to prevent overwriting our node modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=eluedev
      - MONGO_PASSWORD=wisdom123
    command: npm run dev
  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eluedev
      - MONGO_INITDB_ROOT_PASSWORD=wisdom123
