# would contain configurations that are shared between enviroments
version: "3"
services:
  node-app: # 1st service
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  database: # 2nd service
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eluedev
      - MONGO_INITDB_ROOT_PASSWORD=wisdom123
    volumes:
      - mongo-db:/data/db #adding mongo-db: make it a named volume, unlike an anonymous volume

# doing this, because multiple services can use this volume, runnning it without adding this line would make it not to work
volumes:
  mongo-db:
