version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - database

  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eluedev
      - MONGO_INITDB_ROOT_PASSWORD=wisdom123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
